default:
  outputs:
    dev:
      type: duckdb
      path:  "md:retailio_db?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 4
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('REGION') }}"
        s3_access_key_id: "{{ env_var('ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('SECRET_KEY') }}"
  target: dev